export const GET_PELANGGAN = 'GET_PELANGGAN';
export const ADD_PELANGGAN = 'ADD_PELANGGAN';
export const GET_PELANGGAN_BY_ID = 'GET_PELANGGAN_BY_ID';
export const EDIT_PELANGGAN = 'EDIT_PELANGGAN';
export const DELETE_PELANGGAN = 'DELETE_PELANGGAN';