export const GET_PENJUALAN = 'GET_PENJUALAN';
export const GET_PENJUALAN_BY_NOTA = 'GET_PENJUALAN_BY_NOTA';
export const ADD_PENJUALAN = 'ADD_PENJUALAN';
export const EDIT_PENJUALAN = 'EDIT_PENJUALAN';
export const DELETE_PENJUALAN = 'DELETE_PENJUALAN';
